### ISSUE TITLE
Possible to display captions?

### ISSUE THREAD

**Issue by Matra-Simca** [jsanahuja/InstagramFeed#14]
Hi - this is brilliant, is it possible to have an option to display captions?

**Comment by jsanahuja** [comment]
Hello, there is no such option for now but might implement it in the future or accept a pull request implementing it.

**Comment by N-Shar-ma** [comment]
Hello, I'd like to fix this issue and was thinking of adding a display_captions option for showing the caption as an overlay when hovering over the image, so that the grid layout is not disturbed. The following pen is a demo:
[https://codepen.io/N-Sharma/pen/BazPyNG?editors=1100](url)

If you are fine with this implementation, I will open a PR for this

**Comment by jsanahuja** [comment]
Sure, send the PR. The only change I would do is removing `top:0` and adding `max-height:100%`

Thanks!
