### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by catinwarmhands** [jsanahuja/InstagramFeed#3]
Hi! Great library - i love how simple api is!
I was wondering if it will be CORS compatible to load more items [this way](https://stackoverflow.com/a/49341049)
Sorry if this is stupid idea, im not very familiar with fancy web programming 😔

**Comment by jsanahuja** [comment]
It is not stupid at all :)
Seems to work without the `after` parameter inside the `variables` json. The problem is that I don't think we can dinamically get the `query_hash` and `id`. Also, if we can, would be about 4 requests to load just an instagram feed.

An other option is to use static query hashes but we don't know the expiry time (if it has) nor if they have traffic limits.

**Comment by catinwarmhands** [comment]
This `query_hash` does not expires and is specific for each request type.

User id can be obtained by hand via `https://www.instagram.com/{{username}}/?__a=1`

Biggest problem is that it seems to be unofficial api, so nobody knows how reliable is it.
