### ISSUE TITLE
InstagrafeedFeed don't working 

### ISSUE THREAD

**Issue by erreortega** [jsanahuja/InstagramFeed#47]
Hello Everyone, I notice some issues through in this week. Images don't load on any .js files (jquery or without jquery). The cause, probably, come from instagram and your repeatedly updates.

Can u guys check?

Thx!

**Comment by erreortega** [comment]
Wow, everyone is back up and running at this point - including the page with the demos. 

(hidden cause Insta dont work again)

**Comment by jhvanderschee** [comment]
If you only need a very basic solution without messing with the API, you can try profilepageimages.usecuec.com. We kept it very basic and use the new Instagram API so you don't have to. Otherwise, just stick around until this thing is working again.

**Comment by jhvanderschee** [comment]
This tool is not working in (my) Firefox. Firefox blocks almost all functionality because of its native anti-tracking rules and so do all ad-blockers. I hope and expect this 'blocking' to increase over time. Apart from the fact that this tool (already) does not work for a substantial part of the internet, it also tricks its visitors into the mass surveillance system Facebook has created. Finally, the image retrieval from Facebook slows websites down and makes them violate the law in the EU. I think you should warn people for that... What do you think?

**Comment by jsanahuja** [comment]
This is usually because you've been banned. Should happen less times with the [2.0.1 release](https://github.com/jsanahuja/InstagramFeed/releases/tag/2.0.1) as of we have implemented client-side caching in #54.
