### ISSUE TITLE
Implement client-side caching using localStorage

### ISSUE THREAD

**Issue by jsanahuja** [jsanahuja/InstagramFeed#49]
The purpose of this issue is implementing the same done here: https://github.com/jsanahuja/jquery.instagramFeed/pull/97

Feel free to send your PR.

Thanks!

**Comment by piotrmerton** [comment]
Hey @jsanahuja have you seen this https://stackoverflow.com/a/37952998? If querying instagram using this route 

`https://instagram.com/graphql/query/?query_id=17888483320059182&variables={"id":"USERID","first":20,"after":null}` 

there seems to be no request limit and it is possible to query up to 20 images. It uses user ID instead of username. The query id is permanent value and always is 17888483320059182 - unless Instagram chooses to change it in the future, but it seems to work at least from 2017.

Here is related source: https://stackoverflow.com/a/47243409

**Comment by jsanahuja** [comment]
Are you implementing this @RomainDW @Symediane?
